In [8]:
import numpy as np
import torch

In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    x = x.to("cpu")

## Autograd

In [13]:
device = "cpu"
if torch.cuda.is_available():
    device = torch.device("cuda")

In [14]:
x = torch.randn(3,requires_grad=True, device = device)

In [15]:
print(x)

tensor([ 0.2106, -0.4876, -1.8163], device='cuda:0', requires_grad=True)


In [16]:
y = x+2

In [17]:
y

tensor([2.2106, 1.5124, 0.1837], device='cuda:0', grad_fn=<AddBackward0>)

In [18]:
z = y*y*2

In [19]:
z

tensor([9.7732, 4.5745, 0.0675], device='cuda:0', grad_fn=<MulBackward0>)

In [20]:
z = z.mean()

In [21]:
z

tensor(4.8051, device='cuda:0', grad_fn=<MeanBackward0>)

In [22]:
z.backward() # does dz/dx auto
print(x.grad)

tensor([2.9474, 2.0165, 0.2449], device='cuda:0')


In [23]:
x = torch.randn(3,requires_grad=True, device = device)
y = x+2
z = y*y*2
print(z)

tensor([20.6084, 10.4014,  7.5426], device='cuda:0', grad_fn=<MulBackward0>)


In [27]:
# vector jacovian product...?
v = torch.tensor([.1,1,0.001], dtype=torch.float32, device = device)
v

tensor([0.1000, 1.0000, 0.0010], device='cuda:0')

In [28]:
z.backward(v)

In [29]:
print(x.grad)

tensor([1.2840e+00, 9.1220e+00, 7.7679e-03], device='cuda:0')


## Backprop

In [30]:
x = torch.tensor(1.0, device = device)
y = torch.tensor(2.0,device = device)

w = torch.tensor(1.0, requires_grad = True, device = device)

# fwd
ycap = w*x
loss = (ycap-y)**2

print(loss)

tensor(1., device='cuda:0', grad_fn=<PowBackward0>)


In [31]:
# bkwd
loss.backward()
print(w.grad)

tensor(-2., device='cuda:0')


## autoShiz

In [32]:
# design model(input,output size, fwd pass (layers))
# construct loss and optimizer
# training loop
## fwd pass
## .backward()
## update wt

In [44]:
import torch.nn as nn

# model
X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32, device = device)
Y = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32, device = device)

Xtest = torch.tensor([[5]], dtype=torch.float32, device = device)

n_samples, n_features = X.shape
print(n_samples, n_features)

ipSize = n_features
opSize = n_features
model = nn.Linear(ipSize, opSize, device = device)



# loss:
loss = nn.MSELoss()

# opt
# opt = torch.optim.SGD([w],lr=0.01)
opt = torch.optim.SGD(model.parameters(),lr=0.01)


# How to predict?:
print(model(Xtest))
epochs = 100
for epoch in range(epochs):
    # smthing fwd
    ycap = model(X)
    
    # loss
    l = loss(y,ycap)
    
    # bkd
    l.backward()
    
    # step
    opt.step()
    
    # zero grad
    opt.zero_grad()
    
    if epoch%10 == 0:
        w,b = model.parameters()
        print(w[0].item(),epoch, l.item())

yTest = torch.tensor([[10]], dtype=torch.float32, device = device)
with torch.no_grad():
    ycap = model(Xtest)
    print(ycap)
    acc = (yTest-ycap)/float(yTest.shape[0])
    print(acc)

4 1
tensor([[5.6265]], device='cuda:0', grad_fn=<AddmmBackward>)
0.8730513453483582 0 2.6617393493652344
0.5076146721839905 10 0.34249240159988403
0.4379883110523224 20 0.2665614187717438
0.4162631332874298 30 0.24959738552570343
0.4025537371635437 40 0.23503205180168152
0.3904353976249695 50 0.22135096788406372
0.3788658380508423 60 0.20846717059612274
0.36766862869262695 70 0.19633325934410095
0.3568071722984314 80 0.18490566313266754
0.34626737236976624 90 0.1741432398557663
tensor([[2.6943]], device='cuda:0')
tensor([[7.3057]], device='cuda:0')


## Minibatches

In [45]:
import torchvision
from torch.utils.data import Dataset, DataLoader
import math

In [46]:
# torchvision.transforms.Compose([class1(),class2(),...])

In [ ]:
# softmax
# outputs = torch.softmax(x, dim=0) but don't do this, Xent of torch will auto apply

# Xent:
loss = nn.CrossEntropyLoss()
# nn.LogSoftmax + nnNLLLoss
# y shouldn't be one hotencoded
# 
Y = torch.tensor([[0.5,2.0,0.3]], device = device)
#l1 =  

# while flatenning you do -1, 16*5*5